version: 2

project_name: dbrest

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/dbrest
    binary: dbrest
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"

brews:
  - name: dbrest
    directory: Formula
    repository:
      owner: timkrase
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/timkrase/dbrest-cli"
    description: "Query Deutsche Bahn transport data from the DB transport REST API."
    install: |
      bin.install "dbrest"
    test: |
      system "#{bin}/dbrest", "--version"
